Applied patch from SourceForge (#1722924, Date Submitted: 2007-05-21 20:48, Date Last Updated: 2007-06-17 15:59):
Compilation fails Linux kernels > 2.6.18 because of config.h

After kernel-2.6.16 it is impossible for me to compile opencbm 4.0.

Upon trying make -f LINUX/Makefile I get:

CC [M] /home/dl/opencbm-0.4.0/sys/linux/cbm_module.o
/home/dl/opencbm-0.4.0/sys/linux/cbm_module.c:23:26: linux/config.h: No
such file or directory
/home/dl/opencbm-0.4.0/sys/linux/cbm_module.c:111: error: syntax error
before string constant

So two problems there, firstly /usr/src/linux/include/linux/config.h is
obsolete and does not exist anymore.

This fix is easy, just locate the cbm_module.c and replace #include
<linux/config.h> with #include <linux/autoconf.h>

(Done it in a backwards-compatible way)